export const RESET_LOGIN_STORE = 'RESET_LOGIN_STORE';

export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';

export const DO_LOGIN_REQUEST = 'DO_LOGIN_REQUEST';
export const DO_LOGIN_SUCCESS = 'DO_LOGIN_SUCCESS';
export const DO_LOGIN_FAILURE = 'DO_LOGIN_FAILURE';
