export const RESET_ROUTES_STORE = 'RESET_ROUTES_STORE';

export const RESET_LOCATIONS = 'RESET_LOCATIONS';

export const CLEAR_ROUTES_ERROR = 'CLEAR_ROUTES_ERROR';

export const GET_ROUTES_REQUEST = 'GET_ROUTES_REQUEST';
export const GET_ROUTES_SUCCESS = 'GET_ROUTES_SUCCESS';
export const GET_ROUTES_FAILURE = 'GET_ROUTES_FAILURE';

export const FIND_LOCATION_REQUEST = 'FIND_LOCATION_REQUEST';
export const FIND_LOCATION_SUCCESS = 'FIND_LOCATION_SUCCESS';
export const FIND_LOCATION_FAILURE= 'FIND_LOCATION_FAILURE';

export const FIND_ROUTES_REQUEST = 'FIND_ROUTES_REQUEST';
export const FIND_ROUTES_SUCCESS = 'FIND_ROUTES_SUCCESS';
export const FIND_ROUTES_FAILURE = 'FIND_ROUTES_FAILURE';

export const SELECT_ROUTE_REQUEST = 'SELECT_ROUTE_REQUEST';
export const SELECT_ROUTE_SUCCESS = 'SELECT_ROUTE_SUCCESS';
export const SELECT_ROUTE_FAILURE = 'SELECT_ROUTE_FAILURE';

export const SELECT_STARTING_POSITION = 'SELECT_STARTING_POSITION';

export const SELECT_DESTINATION = 'SELECT_DESTINATION';

export const SELECT_MODE = 'SELECT_MODE';
