export const RESET_STATISTICS_STORE = 'RESET_STATISTICS_STORE';

export const CLEAR_STATISTICS_ERROR = 'CLEAR_STATISTICS_ERROR';

export const GET_STATISTICS_REQUEST = 'GET_STATISTICS_REQUEST';
export const GET_STATISTICS_SUCCESS = 'GET_STATISTICS_SUCCESS';
export const GET_STATISTICS_FAILURE = 'GET_STATISTICS_FAILURE';
